//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerTools.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class careertoolsEntities : DbContext
    {
        public careertoolsEntities()
            : base("name=careertoolsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<RecruitingCompany> RecruitingCompanies { get; set; }
        public virtual DbSet<Refer> Refers { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
    }
}
