//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int ContactID { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int RecruitingCompanyFK { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual RecruitingCompany RecruitingCompany { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
