//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int JobID { get; set; }
        public string UserID { get; set; }
        public string JobTitle { get; set; }
        public int Company { get; set; }
        public int ReferType { get; set; }
        public int Priority { get; set; }
        public int TermFK { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual Refer Refer { get; set; }
        public virtual Term Term { get; set; }
    }
}
