//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitingCompany
    {
        public RecruitingCompany()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int RecruitingCompanyID { get; set; }
        public string UserID { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
